version: '2'
services:
  nginx:
    image: nginx
    ports:
      - 8000:80
    volumes:
      - ./tll-service/.docker/images/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./tll-service/.docker/logs/nginx/:/var/log/nginx
    links:
      - php
    volumes_from:
      - php
    depends_on:
      - php

  php:
    build: ./tll-service
    environment:
      SYMFONY_ENV: prod
    links:
      - db
    volumes:
      - ./tll-service:/var/www
      - ./tll-service/.docker/images/php-fpm/php-ini-overrides.ini:/usr/local/etc/php/conf.d/99-overrides.ini
    working_dir: /var/www
    depends_on:
      - db

  db:
    image: mysql
    ports:
      - "3306:3307"
    volumes:
      - db:/data/db
      - ./.docker/images/mysql/mysqld.cnf:/etc/mysql/conf.d/mysqld.cnf
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: tll
      MYSQL_USER: tll
      MYSQL_PASSWORD: tll

  web:
    build: ./tll-webapp
    ports:
      - 80:80

volumes:
  db:
  php:
